stages:
  - build
  - test

before_script:
  - rustup update
  - apt-get update && apt-get upgrade -y && apt-get install -y fuse libfuse-dev

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose
    - cargo test --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true

test-suite:
  stage: test
  image: rust:latest
  script:
    - cargo build --verbose
    - sh test-suite/all.sh
