[workspace]
members = [
    "fal-backend-apfs",
    "fal-backend-btrfs",
    "fal-backend-ext4",
    "fal-frontend-fuse",
    "fal-frontend-fuse/libaio-sys",
    "fal-frontend-redox",
    "fal",

    # TODO: Temporary, for testing individual early WIP filesystems.
    "btrfs-test",
]
