[package]
name = "fal-frontend-fuse"
version = "0.1.0"
authors = ["4lDO2 <4lDO2@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fal = { path = "../fal", version = "0.1" }
libc = "0.2"
time = "0.1"
fuse = "0.3"
