[package]
name = "fal-frontend-redox"
version = "0.1.0"
authors = ["4lDO2 <4lDO2@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redox_syscall = "0.1"
fal = { path = "../fal", version = "0.1" }
